# Generated by Django 4.2.19 on 2025-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_title', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=200, upload_to='images/project_images/')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('finished', 'Finished')], default='new', max_length=10)),
                ('type', models.CharField(choices=[('center', 'Center'), ('customer', 'Customer')], default='', max_length=15)),
                ('service', models.CharField(choices=[('car', 'Car'), ('home', 'Home')], default='', max_length=15)),
            ],
        ),
    ]
