# Generated by Django 4.2.19 on 2025-02-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
